var REFRESH_TIME = 5000;
var LIST_OF_SCHEDULERS = [
	"http://10.144.144.21:4567/api/",
	"http://10.144.144.22:4567/api/",
	"http://10.144.144.23:4567/api/"
];

var CURRENT_SCHEDULER_INDEX = 0;
var FAILED_ATTEMPTS = 0;

function SCHEDULER_API_URL() {
	if(FAILED_ATTEMPTS > LIST_OF_SCHEDULERS.length) {
		alert("All schedulers failed to respond.");
	}
	return LIST_OF_SCHEDULERS[CURRENT_SCHEDULER_INDEX];
}

function RESET_FAILED_ATTEMPTS() {
	FAILED_ATTEMPTS = 0;
}

function NEXT_SCHEDULER_URL() {
	CURRENT_SCHEDULER_INDEX++;
	FAILED_ATTEMPTS++;
	if(CURRENT_SCHEDULER_INDEX >= LIST_OF_SCHEDULERS.length) {
		CURRENT_SCHEDULER_INDEX = 0;
	}
	$.cookie("SCHEDULER_API_INDEX", CURRENT_SCHEDULER_INDEX);
}

if($.cookie("SCHEDULER_API_INDEX") != undefined) {
	CURRENT_SCHEDULER_INDEX = $.cookie("SCHEDULER_API_INDEX");
} else {
	$.cookie("SCHEDULER_API_INDEX", CURRENT_SCHEDULER_INDEX);
}